### ISSUE TITLE
로그인 이후 멈춤 현상 (student 옵션)

### ISSUE THREAD

**Issue by rlarbduq777** [KMJ901122/KNUAutoCheckLab#1]
프로그램이 멈춘 위치 (student 옵션 적용)
![image](https://user-images.githubusercontent.com/23810688/116515924-e95d4080-a907-11eb-9a19-ee3c3c0ad6ea.png)

--- 터미널 오류 창 ---
DevTools listening on ws://127.0.0.1:12951/devtools/browser/9472de18-d570-4c8e-a862-539f1782f6eb
Traceback (most recent call last):
  File "c:\Users\rlarb\Desktop\git\KNUAutoCheckLab\lab_auto.py", line 37, in <module>
    d.find_element_by_id('btnUser').click()
  File "C:\Users\rlarb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\rlarb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\rlarb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rlarb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="btnUser"]"}
  (Session info: chrome=90.0.4430.93)

PS C:\Users\rlarb> [28016:14916:0429/160647.086:ERROR:device_event_log_impl.cc(214)] [16:06:47.086] USB: usb_device_handle_win.cc:1054 
Failed to read descriptor from node connection: 시스템에 부착된 장치가 작동하지 않습니다. (0x1F)
[28016:14916:0429/160647.089:ERROR:device_event_log_impl.cc(214)] [16:06:47.089] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: 시스템에 부착된 장치가 작동하지 않습니다. (0x1F)
[28016:14916:0429/160647.090:ERROR:device_event_log_impl.cc(214)] [16:06:47.091] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: 시스템에 부착된 장치가 작동하지 않습니다. (0x1F)

**Comment by rlarbduq777** [comment]
#2 로 해결 가능
